alias: Dashboard cheat code
description: ""
trigger:
  - platform: state
    entity_id:
      - input_button.up_button
condition: []
action:
  - wait_for_trigger:
      - platform: state
        entity_id:
          - input_button.up_button
  - wait_for_trigger:
      - platform: state
        entity_id:
          - input_button.down_button
  - wait_for_trigger:
      - platform: state
        entity_id:
          - input_button.down_button
  - wait_for_trigger:
      - platform: state
        entity_id:
          - input_button.left_button
  - wait_for_trigger:
      - platform: state
        entity_id:
          - input_button.right_button
  - wait_for_trigger:
      - platform: state
        entity_id:
          - input_button.left_button
  - wait_for_trigger:
      - platform: state
        entity_id:
          - input_button.right_button
  - wait_for_trigger:
      - platform: state
        entity_id:
          - input_button.start_button
  - wait_for_trigger:
      - platform: state
        entity_id:
          - input_button.select_button
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.secret_unlocked
    data: {}
    enabled: true
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
    enabled: true
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.secret_unlocked
    data: {}
    enabled: true
mode: single